package com.ruby.sun.bean;
// Generated 12-Apr-2018 1:36:38 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DeptEmpLatestDate generated by hbm2java
 */
@Entity
@Table(name = "dept_emp_latest_date", catalog = "employees")
public class DeptEmpLatestDate implements java.io.Serializable {

	private DeptEmpLatestDateId id;

	public DeptEmpLatestDate() {
	}

	public DeptEmpLatestDate(DeptEmpLatestDateId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "empNo", column = @Column(name = "emp_no", nullable = false)),
			@AttributeOverride(name = "fromDate", column = @Column(name = "from_date", length = 10)),
			@AttributeOverride(name = "toDate", column = @Column(name = "to_date", length = 10)) })
	public DeptEmpLatestDateId getId() {
		return this.id;
	}

	public void setId(DeptEmpLatestDateId id) {
		this.id = id;
	}

}
